version: '3.9'
services:
  mib_messages:
    container_name: message_microservice
    build:
      context: ../MMIB-Message-Submodule
      dockerfile: ../MMIB-Message-Submodule/Dockerfile
    ports:
      - "5002:5002"
  redis_messages:
    container_name: redis_messages
    image: "redis:alpine"
    command: --port 6378
    ports:
      - "6378:6378"
  celery_messages:
    container_name: celery_messages
    build:
      context: ../MMIB-Message-Submodule
      dockerfile: ../MMIB-Message-Submodule/DockerfileCelery
    depends_on:
      - redis_messages
    links:
      - redis_messages
