# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from message_server.models.base_model_ import Model
from message_server import util


class Draft(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, id: int=None, sender_mail: str=None,
                 receiver_mail: str=None, message: str=None,
                 time: str=None, image: str=None,
                 image_hash: str=None):  # noqa: E501
        """Draft - a model defined in Swagger

        :param id: The id of this Draft.  # noqa: E501
        :type id: int
        :param sender_mail: The sender_mail of this Draft.  # noqa: E501
        :type sender_mail: str
        :param receiver_mail: The receiver_mail of this Draft.  # noqa: E501
        :type receiver_mail: str
        :param message: The message of this Draft.  # noqa: E501
        :type message: str
        :param time: The time of this Draft.  # noqa: E501
        :type time: str
        :param image: The image of this Draft.  # noqa: E501
        :type image: str
        :param image_hash: The base64 encoding of the image file
        :type image_hash: str
        """
        self.swagger_types = {
            'id': int,
            'sender_mail': str,
            'receiver_mail': str,
            'message': str,
            'time': str,
            'image': str,
            'image_hash': str
        }

        self.attribute_map = {
            'id': 'id',
            'sender_mail': 'sender_mail',
            'receiver_mail': 'receiver_mail',
            'message': 'message',
            'time': 'time',
            'image': 'image',
            'image_hash': 'image_hash'
        }

        self._id = id
        self._sender_mail = sender_mail
        self._receiver_mail = receiver_mail
        self._message = message
        self._time = time
        self._image = image
        self._image_hash = image_hash

    @classmethod
    def from_dict(cls, dikt) -> 'Draft':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Draft of this Draft.  # noqa: E501
        :rtype: Draft
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this Draft.


        :return: The id of this Draft.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this Draft.


        :param id: The id of this Draft.
        :type id: int
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def sender_mail(self) -> str:
        """Gets the sender_mail of this Draft.


        :return: The sender_mail of this Draft.
        :rtype: str
        """
        return self._sender_mail

    @sender_mail.setter
    def sender_mail(self, sender_mail: str):
        """Sets the sender_mail of this Draft.


        :param sender_mail: The sender_mail of this Draft.
        :type sender_mail: str
        """

        self._sender_mail = sender_mail

    @property
    def receiver_mail(self) -> str:
        """Gets the receiver_mail of this Draft.


        :return: The receiver_mail of this Draft.
        :rtype: str
        """
        return self._receiver_mail

    @receiver_mail.setter
    def receiver_mail(self, receiver_mail: str):
        """Sets the receiver_mail of this Draft.


        :param receiver_mail: The receiver_mail of this Draft.
        :type receiver_mail: str
        """

        self._receiver_mail = receiver_mail

    @property
    def message(self) -> str:
        """Gets the message of this Draft.


        :return: The message of this Draft.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message: str):
        """Sets the message of this Draft.


        :param message: The message of this Draft.
        :type message: str
        """

        self._message = message

    @property
    def time(self) -> str:
        """Gets the time of this Draft.


        :return: The time of this Draft.
        :rtype: str
        """
        return self._time

    @time.setter
    def time(self, time: str):
        """Sets the time of this Draft.


        :param time: The time of this Draft.
        :type time: str
        """

        self._time = time

    @property
    def image(self) -> str:
        """Gets the image of this Draft.


        :return: The image of this Draft.
        :rtype: str
        """
        return self._image

    @image.setter
    def image(self, image: str):
        """Sets the image of this Draft.


        :param image: The image of this Draft.
        :type image: str
        """

        self._image = image

    @property
    def image_hash(self) -> str:
        """Gets the image_hash of this Draft.


        :return: The image_hash of this Draft.
        :rtype: str
        """
        return self._image_hash

    @image_hash.setter
    def image_hash(self, image_hash: str):
        """Sets the image_hash of this Draft.


        :param image_hash: The image_hash of this Draft.
        :type image_hash: str
        """

        self._image_hash = image_hash
